# Generated by Django 5.1.7 on 2025-11-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default='Sin contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='sin contenido', max_length=100),
            preserve_default=False,
        ),
    ]
