# Generated by Django 5.1.7 on 2025-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='valor',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ropa',
            name='fecha_fabricacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='talla',
            field=models.CharField(max_length=10),
        ),
    ]
